### PR TITLE
swift assignment

### PR DESCRIPTION
**Pull request by zzyptr**

### CODE REVIEW

**Comment by gao-sun** [comment]
Type "Dyson" and got nothing, would you mind to double check if everything works as expected?

image

**Comment by zzyptr** [comment]
> Type "Dyson" and got nothing, would you mind to double check if everything works as expected?
> 
> 
> 
> image

Please try Stock App again

**Comment by gao-sun** [comment]
it works, thanks. please leave your contact info we'll touch you soon.

you can leave in base64 and delete once we send you email.

**Comment by zzyptr** [comment]
> it works, thanks. please leave your contact info we'll touch you soon.
> 
> 
> 
> you can leave in base64 and delete once we send you email.

zzyptr@gmail.com

**Comment by gao-sun** [comment]
gotcha. you can delete it safely

**Comment by Jamesliyuan** [comment]
Dear Sun,


Thanks a lot for your reply.


You could contact me with email or mobile phone at 18611770926.


Regards,


Li Yuan










At 2020-09-20 13:30:36, "gao-sun" <notifications@github.com> wrote:

it works, thanks. please leave your contact info we'll touch you soon.

you can leave in base64 and delete once we send you email.

**Pull request closed without merging**
